##data <- read.csv('E:/saad/parhai/Go remote/covid.csv', header = T)
plot(data)
str(data)
install.packages('corrplot')
install.packages('ggplot')
library(ggplot2)
library(ggplot)
library(corrplot)
library(dplyr)

data %>% select_if(is.numeric) %>%  cor() %>% corrplot()
ggplot(data)+geom_boxplot(aes(x= Province,y = Cases))
ggplot(data) + geom_bar(aes(x = Cases , fill = Province))
data$Date = as.numeric(data$Date)
