SALE2 = read.csv("pr21.csv", header = T)
library(ggplot2)
library(ggplot)
library(corrplot)
library(data.table)
library(readr)
library(dplyr)
library(stringr)
library(stringi)
str(SALE21)
summary(SALE21)

SALE21$Date = as.Date(SALE21$Date)
hist(SALE21$Quantity..MT.)
hist(SALE21$Gross.Profit)
summary(SALE21$Quantity..MT.)
hist(log(SALE21$Quantity..MT.))
SALE21$dummy = as.factor(SALE21$Quantity..MT.)
summary(SALE21$dummy)
SALE21$COST.RATE = as.numeric(SALE21$COST.RATE)
ggplot(SALE21, aes(x = Oder.Type, y = Quantity..MT., fill = Sales.Person)) + geom_boxplot()
SALE21[sapply(SALE21, is.character)] <- lapply(SALE21[sapply(SALE21, is.character)], 
                                           as.factor)
ggplot(SALE21, aes(x = Oder.Type, y = Quantity..MT., fill = Sales.Person)) + geom_boxplot()
s33=SALE21[,c(2:17)]
str(s33)
#sl$BRAND = word(sl$Description, 1,7, sep=" ")
#sl$PACKAGE_SIZE = word(sl$Description, 8,10 , sep=" ")
summary(s33$Description)
s33$dia = as.factor(word(s33$Description, 1,7, sep=" "))
s33$length = word(s33$Description, 8,10 , sep=" ")
summary(s33$dia)

OUTLIER = s33 %>% filter(c(Quantity..MT. < 3, Quantity..MT. > 100))
s33$OUTLIER = ifelse(c(s33$Quantity..MT. < 3,, "YES" , "NO"))
s33$OUTLIER = ifelse(s33$Quantity..MT. > 100, "YES" , "NO")
summary(s33$OUTLIER)
Q <- quantile(s33$Quantity..MT., probs=c(.05, .995), na.rm = FALSE)
boxplot(Q)
boxplot(s33$Quantity..MT.)
summary(s33$Quantity..MT.)
summary(SALE21$Quantity..MT.)
summary(Q)
analysis_date = max(s33$Date)
sRFM <- s33 %>% 
  group_by(Customer.Name) %>% 
  summarise(recency=as.numeric(analysis_date-max(Date)),
            frequency =n_distinct(SO.Number), monetary= mean(Gross.Profit), sum(Gross.Profit),mean(Quantity..MT.))
s33$Date = as.Date(s33$Date)
str(s33)
View(sRFM)
summary(s33$dia)
summary(s33$Sales.Segment)
ggplot(s33, aes(x=Date, y=Gross.Profit, group=Sales.Segment)) +geom_line(aes(color=Sales.Segment))
ggplot(s33, aes(x=Date, y=Quantity..MT., group=Sales.Segment)) +geom_line(aes(color=Sales.Segment))
View(s33)

summary(s33$Quantity..MT.)